theme: cinder

site_name: Bullet
repo_url: https://github.com/yahoo/bullet-docs

pages:
- Home: index.md
- Quick Start: quick-start.md
- Backend:
  - Storm Architecture: backend/storm-architecture.md
  - Getting your data into Bullet: backend/ingestion.md
  - Setup on Storm: backend/setup-storm.md
  - Tuning: backend/tuning.md
- REST API:
  - Setup: ws/setup.md
  - API: ws/api.md
  - Examples: ws/examples.md
- UI:
  - Setup: ui/setup.md
  - Usage: ui/usage.md
- About:
  - Past Releases: about/releases.md
  - Contributing: about/contributing.md
  - Contact Us: about/contact.md

markdown_extensions:
    - admonition

extra:
  collapse_toc: true
  toc_depth: 5
  include_search: true

extra_css:
  - css/extra.css

copyright: "Bullet is licensed under the <a href='https://github.com/yahoo/bullet/blob/master/LICENSE'>Apache 2 license"
