# Custom settings for the example
# Settings not overridden will default to the defaults in bullet_defaults.yaml in the bullet-storm artifact
bullet.topology.function: "bullet"
bullet.topology.name: "bullet"
bullet.topology.metrics.enable: false
bullet.topology.metrics.built.in.enable: false
bullet.topology.drpc.spout.parallelism: 1
bullet.topology.drpc.spout.cpu.load: 20.0
bullet.topology.drpc.spout.memory.on.heap.load: 256.0
bullet.topology.drpc.spout.memory.off.heap.load: 192.0
bullet.topology.prepare.bolt.parallelism: 1
bullet.topology.prepare.bolt.cpu.load: 10.0
bullet.topology.prepare.bolt.memory.on.heap.load: 128.0
bullet.topology.prepare.bolt.memory.off.heap.load: 192.0
bullet.topology.filter.bolt.parallelism: 1
bullet.topology.filter.bolt.cpu.load: 100.0
bullet.topology.filter.bolt.memory.on.heap.load: 256.0
bullet.topology.filter.bolt.memory.off.heap.load: 192.0
bullet.topology.return.bolt.parallelism: 1
bullet.topology.return.bolt.cpu.load: 10.0
bullet.topology.return.bolt.memory.on.heap.load: 128.0
bullet.topology.return.bolt.memory.off.heap.load: 192.0
bullet.topology.join.bolt.parallelism: 1
bullet.topology.join.bolt.cpu.load: 20.0
bullet.topology.join.bolt.memory.on.heap.load: 128.0
bullet.topology.join.bolt.memory.off.heap.load: 192.0
bullet.topology.join.bolt.error.tick.timeout: 3
bullet.topology.join.bolt.rule.tick.timeout: 3
bullet.topology.tick.interval.secs: 1
bullet.rule.aggregation.count.distinct.sketch.entries: 16384
bullet.rule.aggregation.group.sketch.entries: 512
bullet.result.metadata.enable: true
bullet.result.metadata.metrics:
    - name: "Rule Identifier"
      key: "rule_id"
    - name: "Creation Time"
      key: "rule_receive_time"
    - name: "Termination Time"
      key: "rule_finish_time"
    - name: "Aggregation Metadata"
      key: "aggregation"
    - name: "Estimated Result"
      key: "wasEstimated"
    - name: "Standard Deviations"
      key: "standardDeviations"
    - name: "Sketch Size"
      key: "sketchSize"
    - name: "Sketch Theta"
      key: "sketchTheta"
    - name: "Uniques Estimate"
      key: "uniquesEstimate"
bullet.record.inject.timestamp.enable: true
bullet.record.inject.timestamp.key: "__receive_timestamp"
